INSERT INTO ZAFFA_TEAM.Rol (NOMBRE_ROL, ESTADO_ROL)
VALUES ('Cliente', 'A')

INSERT INTO ZAFFA_TEAM.Rol (NOMBRE_ROL, ESTADO_ROL)
VALUES ('Administrativo', 'A')

select *
FROM ZAFFA_TEAM.Rol

INSERT INTO ZAFFA_TEAM.Funcionalidad (FUNCIONALIDAD_DESCRIPCION) VALUES ('AbmRol');
INSERT INTO ZAFFA_TEAM.Funcionalidad (FUNCIONALIDAD_DESCRIPCION) VALUES ('AbmCrucero');
INSERT INTO ZAFFA_TEAM.Funcionalidad (FUNCIONALIDAD_DESCRIPCION) VALUES ('AbmPuerto');
INSERT INTO ZAFFA_TEAM.Funcionalidad (FUNCIONALIDAD_DESCRIPCION) VALUES ('AbmRecorrido');
INSERT INTO ZAFFA_TEAM.Funcionalidad (FUNCIONALIDAD_DESCRIPCION) VALUES ('CompraReservaPasaje');
INSERT INTO ZAFFA_TEAM.Funcionalidad (FUNCIONALIDAD_DESCRIPCION) VALUES ('GeneracionViaje');
INSERT INTO ZAFFA_TEAM.Funcionalidad (FUNCIONALIDAD_DESCRIPCION) VALUES ('ListadoEstadistico');
INSERT INTO ZAFFA_TEAM.Funcionalidad (FUNCIONALIDAD_DESCRIPCION) VALUES ('PagoReserva');

--INSERT INTO ZAFFA_TEAM.[Funcionalidad x Rol] 

--INSERT INTO ZAFFA_TEAM.Administrativo (USERNAME, PASS_WORD, INTENTOS_FALLIDOS, NOMBRE_ROL, ESTADO_ADMIN) 

INSERT ZAFFA_TEAM.Cliente (CLI_NOMBRE, CLI_APELLIDO, CLI_DNI, CLI_FECHA_NAC, CLI_DIRECCION, CLI_MAIL, CLI_TELEFONO, NOMBRE_ROL)
SELECT DISTINCT CLI_NOMBRE, CLI_APELLIDO, CLI_DNI, CLI_FECHA_NAC, CLI_DIRECCION, CLI_MAIL, CLI_TELEFONO, 'Cliente'
FROM gd_esquema.Maestra

INSERT ZAFFA_TEAM.Puerto (NOMBRE_PUERTO, ESTADO_PUERTO)
SELECT DISTINCT PUERTO_DESDE, 'A'
FROM gd_esquema.Maestra 

INSERT ZAFFA_TEAM.Marca (CRUCERO_FABRICANTE)
SELECT DISTINCT CRU_FABRICANTE
FROM gd_esquema.Maestra

INSERT ZAFFA_TEAM.Tipo_Cabina (CABINA_TIPO_DESCRIPCION, CABINA_TIPO_RECARGO)
SELECT DISTINCT CABINA_TIPO, CABINA_TIPO_PORC_RECARGO
FROM gd_esquema.Maestra

/*CREATE FUNCTION CANTIDAD_CABINAS(@CRUCERO_ID nvarchar(50))
RETURNS int as 
BEGIN
DECLARE @a int
SET @a = 5
END
RETURN @a
END
*/

INSERT ZAFFA_TEAM.Crucero (CRUCERO_ID, CRUCERO_MODELO, CRUCERO_MARCA_ID, ESTADO_CRUCERO, CANTIDAD_CABINAS, FECHA_ALTA, FECHA_FUERA_DE_SERVICIO, FECHA_REINICIO_DE_SERVICIO, FECHA_BAJA_DEFINITIVA)
SELECT DISTINCT m.CRUCERO_IDENTIFICADOR, 
				m.CRUCERO_MODELO,
				(SELECT DISTINCT CRUCERO_MARCA_ID
					FROM ZAFFA_TEAM.Marca
					WHERE CRUCERO_FABRICANTE = m.CRU_FABRICANTE),
				'A'
				--COUNT(m.CRUCERO_IDENTIFICADOR) CANTIDAD_CABINAS
				--ZAFFA_TEAM.CANTIDAD_CABINAS(m.CRUCERO_IDENTIFICADOR),
				--(SELECT DISTINCT CRUCERO_ID
				--		FROM ZAFFA_TEAM.Cabina
				--		WHERE m.CRUCERO_IDENTIFICADOR = CRUCERO_ID)

FROM gd_esquema.Maestra m


