USE [GD1C2019]
GO

-- BORRAR LOS DATOS DE LAS TABLAS
--DELETE FROM ZAFFA_TEAM.Auditoria_estado_cruceros
DELETE FROM ZAFFA_TEAM.Administrativo
DELETE FROM ZAFFA_TEAM.[Funcionalidad x Rol]
DELETE FROM ZAFFA_TEAM.Funcionalidad
DBCC CHECKIDENT('ZAFFA_TEAM.Funcionalidad', RESEED, 0)
DELETE FROM ZAFFA_TEAM.Rol
DELETE FROM ZAFFA_TEAM.Tramo
DELETE FROM ZAFFA_TEAM.Puerto
DBCC CHECKIDENT('ZAFFA_TEAM.Puerto', RESEED, 0)
DELETE FROM ZAFFA_TEAM.Recorrido_Unico
DELETE FROM ZAFFA_TEAM.Pasaje
DELETE FROM ZAFFA_TEAM.Viaje
DBCC CHECKIDENT('ZAFFA_TEAM.Viaje', RESEED, 0)
DELETE FROM ZAFFA_TEAM.Cabina
DELETE FROM ZAFFA_TEAM.Tipo_Cabina
DELETE FROM ZAFFA_TEAM.Cliente
DBCC CHECKIDENT('ZAFFA_TEAM.Cliente', RESEED, 0)
DELETE FROM ZAFFA_TEAM.Crucero
DELETE FROM ZAFFA_TEAM.Marca
DBCC CHECKIDENT('ZAFFA_TEAM.Marca', RESEED, 0)
DELETE FROM ZAFFA_TEAM.Reserva

-- ELIMINAR LAS TABLAS
DROP TABLE [ZAFFA_TEAM].[Reserva]
GO

DROP TABLE [ZAFFA_TEAM].[Pasaje]
GO

DROP TABLE [ZAFFA_TEAM].[Cliente]
GO

DROP TABLE [ZAFFA_TEAM].[Viaje]
GO

DROP TABLE [ZAFFA_TEAM].[Cabina]
GO

DROP TABLE [ZAFFA_TEAM].[Crucero]
GO

DROP TABLE [ZAFFA_TEAM].[Marca]
GO

DROP TABLE [ZAFFA_TEAM].[Tipo_Cabina]
GO

DROP TABLE [ZAFFA_TEAM].[Tramo]
GO

DROP TABLE [ZAFFA_TEAM].[Recorrido_Unico]
GO

DROP TABLE [ZAFFA_TEAM].[Puerto]
GO

DROP TABLE [ZAFFA_TEAM].[Funcionalidad x Rol]
GO

DROP TABLE [ZAFFA_TEAM].[Administrativo]
GO

DROP TABLE [ZAFFA_TEAM].[Funcionalidad]
GO

DROP TABLE [ZAFFA_TEAM].[Rol]
GO

--DROP TABLE [ZAFFA_TEAM].[Auditoria_estado_cruceros]
--GO

DROP PROCEDURE ZAFFA_TEAM.sp_guardarCrucero

DROP PROCEDURE ZAFFA_TEAM.sp_guardarPuerto

DROP PROCEDURE ZAFFA_TEAM.sp_generarPasaje

DROP PROCEDURE ZAFFA_TEAM.sp_borrarReservas

DROP PROCEDURE ZAFFA_TEAM.sp_guardarRecorrido

DROP PROCEDURE ZAFFA_TEAM.sp_guardarCabina

DROP PROCEDURE ZAFFA_TEAM.sp_guardarRol

DROP PROCEDURE ZAFFA_TEAM.sp_updatClienteRol

DROP PROCEDURE ZAFFA_TEAM.sp_updateAdministradorRol

DROP PROCEDURE ZAFFA_TEAM.sp_deleteRol

DROP PROCEDURE ZAFFA_TEAM.sp_guardarFuncionalidadxRol

DROP PROCEDURE ZAFFA_TEAM.sp_updateCantCabinas

DROP PROCEDURE ZAFFA_TEAM.sp_udteFuncionalidad

DROP PROCEDURE ZAFFA_TEAM.sp_updateNombreRol

DROP PROCEDURE ZAFFA_TEAM.sp_updateNombreFuncionalidadxRol

DROP PROCEDURE ZAFFA_TEAM.sp_deleteFuncionalidadxRol

DROP PROCEDURE ZAFFA_TEAM.sp_habilitarFuncionalidad

DROP PROCEDURE ZAFFA_TEAM.sp_updateFabCrucero

DROP PROCEDURE ZAFFA_TEAM.sp_guardarViaj

DROP FUNCTION ZAFFA_TEAM.Hashear_Password

DROP PROCEDURE ZAFFA_TEAM.sp_login
 
--DROP TRIGGER ZAFFA_TEAM.Auditoria_de_estado_cruceros